name: Deploy in EC2 via Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy on EC2
    # Runner de la EC2 
    runs-on: self-hosted 

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Test
      run: npm test

    - name: Build app
      run: npm run build

    - name: Deploy to EC2 IP
      run: |
        sudo mkdir -p /var/www/testing-login-jest
        sudo rm -rf /var/www/testing-login-jest/*
        sudo cp -r dist/* /var/www/testing-login-jest/
        sudo chown -R www-data:www-data /var/www/testing-login-jest
